export const screenNames = {
  introduce: 'Introduce',
  panGestureHandler: 'PanGestureHandler',
  interpolateScrollView: 'InterpolateScrollView',
  interpolateColor: 'InterpolateColor',
  pinchGestureHandlerScreen: 'PinchGestureHandlerScreen',
  doubleTap: 'DoubleTap',
  scrollViewFromScratch: 'ScrollViewFromScratch',
  colorPicker: 'ColorPicker',
  circularProgress: 'CircularProgress',
  swipeToDelete: 'SwipeToDelete',
  rippleEffect: 'RippleEffect',
  perspectiveMenu: 'PerspectiveMenu',
  slidingCounter: 'SlidingCounter',
  clock: 'Clock',
  magicLayoutAnimation: 'MagicLayoutAnimation',
  animatedFlatList: 'AnimatedFlatList',
  dropdown: 'Dropdown',
  circularCarouselAnimation: 'CircularCarouselAnimation',
  segmentedControl: 'SegmentedControl',
  shakeText: 'ShakeText',
};
